CREATE TABLE clients (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    phone      VARCHAR(255),
    created_at TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE tasks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    description TEXT,
    status      VARCHAR(255),
    priority    VARCHAR(255),
    deadline    DATE,
    client_id   BIGINT,
    CONSTRAINT fk_tasks_client FOREIGN KEY (client_id) REFERENCES clients (id)
);

CREATE TABLE notes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content    TEXT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    client_id  BIGINT,
    CONSTRAINT fk_notes_client FOREIGN KEY (client_id) REFERENCES clients (id)
);
