CREATE TABLE audit_log (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    who       VARCHAR(255) NOT NULL,
    action    VARCHAR(50) NOT NULL,
    entity    VARCHAR(50) NOT NULL,
    entity_id BIGINT NOT NULL,
    timestamp TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_audit_log_timestamp ON audit_log (timestamp);
