spring:
  application:
    name: mini-crm-backend

  profiles:
    active: dev

app:
  cors:
    allowed-origins: http://localhost:3000

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:minicrm;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  flyway:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://db:5432/minicrm
    username: ${DB_USERNAME:minicrm}
    password: ${DB_PASSWORD:minicrm}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:minicrm-test;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: integration-test
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
